### PR TITLE
dm-lwm2m updates

### PR DESCRIPTION
**Pull request by mike-scott**
- Default workqueue stack raise to 2048
- Allow --client to be used as a partial endpoint name filter in leshan.py
- Introduce CONFIG_FOTA_ENDPOINT_PREFIX for changing the "zmp" portion of the endpoint name to something custom (which can be used with the --client filter for updates)

### CODE REVIEW

**Comment by doanac** [comment]
ci-retest (part of the newer CI stuff i've worked on)

**Comment by doanac** [comment]
Since the CI run names are a little different some of the build 135 will still show up. However, the relevant bits are with build 136: https://ci.foundries.io/projects/development/fota/builds/136

**Comment by mike-scott** [comment]
Looks like the 2 failed compile jobs timed out downloading the toolchain?

**Comment by mike-scott** [comment]
And build 136 failure was "Missing required secrets under(/secrets): osftok"

**Comment by doanac** [comment]
ci-retest (should fix the osftok issue from the last run)

**Comment by doanac** [comment]
@mike-scott - the CI logic still isn't quite right (it didn't compile this branch). I'll take a look at it tomorrow, but don't let this hold up merging the code.

**Comment by doanac** [comment]
ci-retest

@mike-scott feel free to ignore the noise. I've just moved the logic for testing PRs for "zmp-samples" into our ci-scripts public repo. I'm sure some things will break while i iron out the details

**Comment by doanac** [comment]
ci-retest (fix container to run compile job in)

**Comment by doanac** [comment]
ci-retest (github was caching the wrong definition file)

**Comment by doanac** [comment]
ci-retest (container use has to be root so that it can write to /archive)

**Pull request merged**
